### ISSUE TITLE
Context menu stays open after gesture on Windows 7

### ISSUE THREAD

**Issue by Moerges** [marklieberman/foxygestures#174]
Hello there,

first of all, thank you for this great extension, Mark, and for all the support you provide. After having become quite reliant on gestures, Foxy Gestures is a life-saver now that Firefox 57 has rendered my previous gesture extension unusable.

Unfortunately, there is an issue on my end, running Firefox 57.0 (64-bit) and Foxy Gestures 1.0.14: I use the right mouse button as the trigger, and as soon as I release it after drawing a gesture, the context menu pops up and remains open until I click it away manually. I am aware this is similar to the well-documented and -understood limitations in Linux and OSX versions—however, I am on Windows (Windows 7 SP1 64-bit, to be precise), so I am quite sure this isn't supposed to be happening.

I've tried looking into it, but all I can find is users reporting the Linux/OSX problem. Therefore, I assume it is something on my end, and hope some of you knowledgeable folks can point me into the right direction to fix this behaviour.

If you need any further information, please let me know.

Thank you in advance.

Moerges

**Comment by marklieberman** [comment]
Very strange that it's happening on Windows.

1) Make sure you do not have any other gesture addons enabled.
2) Does it always happen, or is it only sometimes? On particular sites, or particular gestures? Particularly Close Tab and Undo Close cmmands have issues that are being worked on or recently fixed and can display the context menu. See #144 for more info.
3) Can you open the browser console (Ctrl+Shift+J) and looks for errors or messages that appear when you complete a gesture?

**Comment by Moerges** [comment]
Hello Mark,

thank you for your reply and for your suggestions. Indeed, it is odd that this is happening on Windows, especially since I haven't found anyone else reporting the issue.

Now, to your followup questions:

1. I did still have FireGestures in my legacy extension list—disabled, of course—, but even after removing it from Firefox (and re-installing Foxy Gestures after a restart, just to be sure), the issue persists.

2. It happens always: every single time I draw a gesture, and with every gesture I use (which are: reload tab, close tab, next tab, previous tab), and on all sites I visit.

3. I've just done some testing with the Browser Console, and there is one thing I've noticed that appears to be related to Foxy Gestures: as soon as Foxy Gestures is enabled, I get the following JS error message upon loading/reloading any website:

Error: WebExtension context not found!   (5) ExtensionParent.jsm:821:13 [The (5) is an icon, white in a red circle.]

Upon clicking on the ExtensionParent.jsm part, the following file is displayed: https://github.com/marklieberman/foxygestures/files/1519690/ExtensionParent.txt (orignal file extension was .jsm.js; I had to rename it so its upload would be accepted here)

Curiously (at least to my layman's eyes), it also happens when no gesture is used at all, for example when I reload a site by hitting F5. Maybe it is still related, though? When I disable Foxy Gestures, the error message no longer appears.

(To ensure the message is indeed caused by Foxy Gestures, I temporarily disabled all other extensions.)

While I cannot garner much from this file, I hope it may still help in getting to the bottom of the issue.

Thank you for any further input.

Moerges

**Comment by marklieberman** [comment]
I don't think "Error: WebExtension context not found!" is the problem. I see it often and it seems to come from something internal to Firefox but it has never caused any interference before.

Let me know if version 1.0.15 does anything to resolve the issue on your end, and if not I will try to put together a Window 7 virtual machine to see if I can reproduce the issue.

**Comment by Moerges** [comment]
Hello Mark,

thank you for looking into my report. Sadly, there is no change with version 1.0.15.

However, please don't burden yourself with setting up a Windows 7 environment; I am quite sure it is something on my end, not a general Windows 7 issue. Otherwise, there would certainly have been others reporting this kind of behaviour.

While it's slightly inconvenient, I can live with clicking away the context menu; it doesn't seem worth you spending a lot of time on trying to find a fix.

Maybe it'll be resolved by a future Firefox update. I'll report back here if there is any change.

Moerges

**Comment by lek1015** [comment]
I've been experiencing this problem too. There is always context menu showing up after a gesture.
As Mark said, I have to do left-click on other spot to make it disappear.
I'm currently using Windows 10 and FF 58.0.1(64bit).

**Comment by trunklebob** [comment]
Chiming in to say it's affecting me as well; Windows 10 Enterprise, Firefox 63.0.3. Only other extension is Tab Mix, but the issue still occurs if that is disabled or removed.

**Comment by Moerges** [comment]
Allow me to take this opportunity to provide a quick update from my end: I have meanwhile moved to Windows 10 (Pro, 64-bit, both versions 1803 and 1809; a fresh installation, not an upgrade) on new hardware, and I am still experiencing the same issue.

(I am currently on Firefox 63.0.3 and Foxy Gestures 1.2.4, but this behaviour has persistently occurred on all versions of Firefox and Foxy Gestures I've used this past year.)

**Comment by GNQG** [comment]
Is this still unresolved? [This](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture) might be related to your problem.

**Comment by trunklebob** [comment]
I can confirm that changing dom.event.contextmenu.enabled fixed the issue for me.

**Comment by Moerges** [comment]
Awesome—setting dom.event.contextmenu.enabled to true resolved the issue of the persisting context menu for me as well. Thank you, GNQG.
